name: 'Python Setup'
description: 'Checkout repo, setup Python, install package with optional extras'
inputs:
  python-version:
    description: 'Python version'
    required: true
  install-extras:
    description: 'Extras group (e.g., dev, docs)'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'
    - name: Upgrade pip
      run: python -m pip install --upgrade pip
      shell: bash
    - name: Install package (extras)
      if: inputs.install-extras != ''
      run: pip install .[${{ inputs.install-extras }}]
      shell: bash
    - name: Install package (base)
      if: inputs.install-extras == ''
      run: pip install .
      shell: bash
