"""Sync root SETUP_GUIDE.md to docs/setup-guide.md

Run in pre-commit or manually to keep documentation site copy current.
"""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "SETUP_GUIDE.md"
DEST = ROOT / "docs" / "setup-guide.md"

HEADER = (
    "# PopHealth Observatory – Setup & Usage Guide\n\n"
    "(Synced from root `SETUP_GUIDE.md` – do not edit this file directly. "
    "Update the root file and re-run sync.)\n\n"
)

MARKER = "<!-- INTERNAL_INSTRUCTIONS_EXCLUDED_FROM_DOCS -->"


def main() -> None:
    if not SOURCE.exists():
        raise SystemExit("Source SETUP_GUIDE.md not found")
    raw = SOURCE.read_text(encoding="utf-8")
    lines = raw.splitlines()

    if MARKER in lines:
        marker_index = lines.index(MARKER)
        public_lines = lines[:marker_index]
    else:
        public_lines = lines

    # Remove duplicate top-level header if present (HEADER already supplies it)
    if public_lines and public_lines[0].startswith("# PopHealth Observatory") and HEADER.startswith(public_lines[0]):
        public_lines = public_lines[1:]

    text = "\n".join(public_lines).rstrip() + "\n"
    # Use source file modified time for stable sync marker so pre-commit doesn't rewrite on every commit
    source_ts = datetime.fromtimestamp(SOURCE.stat().st_mtime, timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    new_content = f"{HEADER}{text}\n---\n\nLast sync (source mtime): {source_ts}\n"
    DEST.parent.mkdir(parents=True, exist_ok=True)
    if DEST.exists() and DEST.read_text(encoding="utf-8") == new_content:
        print(f"No changes for {DEST.relative_to(ROOT)}")
        return
    DEST.write_text(new_content, encoding="utf-8")
    print(f"Synced {SOURCE.name} -> {DEST.relative_to(ROOT)}")


if __name__ == "__main__":  # pragma: no cover
    main()
