"""Sync root CHANGELOG.md to docs/changelog.md

Run in pre-commit or manually to keep documentation site copy current.
Ensures single source of truth for changelog (root CHANGELOG.md).
"""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "CHANGELOG.md"
DEST = ROOT / "docs" / "changelog.md"

HEADER = (
    "# Changelog\n\n"
    "(Synced from root `CHANGELOG.md` – do not edit this file directly. "
    "Update the root file and re-run sync.)\n\n"
)


def main() -> None:
    if not SOURCE.exists():
        raise SystemExit("Source CHANGELOG.md not found")

    raw = SOURCE.read_text(encoding="utf-8")
    lines = raw.splitlines()

    # Remove root-level "## Changelog" header if present (HEADER already supplies it)
    if lines and lines[0].strip().startswith("## Changelog"):
        lines = lines[1:]

    text = "\n".join(lines).strip() + "\n"

    # Use source file modified time for stable sync marker
    source_ts = datetime.fromtimestamp(SOURCE.stat().st_mtime, timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    new_content = f"{HEADER}{text}\n\n---\n\nLast sync (source mtime): {source_ts}\n"

    DEST.parent.mkdir(parents=True, exist_ok=True)
    if DEST.exists() and DEST.read_text(encoding="utf-8") == new_content:
        print(f"No changes for {DEST.relative_to(ROOT)}")
        return

    DEST.write_text(new_content, encoding="utf-8")
    print(f"Synced {SOURCE.name} -> {DEST.relative_to(ROOT)}")


if __name__ == "__main__":  # pragma: no cover
    main()
