name: Autofix Lint

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'  # daily 03:00 UTC

permissions:
  contents: write
  pull-requests: write

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install tooling
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]

      - name: Run formatters
        run: |
          ruff check --fix . || true
          black . || true

      - name: Create patch branch
        id: branch
        run: |
          if git diff --quiet; then
            echo "changes=false" >> $GITHUB_OUTPUT
            exit 0
          fi
          BRANCH="autofix/lint-$(date +%Y%m%d%H%M%S)"
          git checkout -b "$BRANCH"
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m 'chore: lint autofixes'
          git push origin "$BRANCH"
          echo "changes=true" >> $GITHUB_OUTPUT
          echo "branch=$BRANCH" >> $GITHUB_OUTPUT

      - name: Open / update PR
        if: steps.branch.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: lint autofixes'
          branch: ${{ steps.branch.outputs.branch }}
          title: 'chore: lint autofixes'
          body: 'Automated Ruff/Black fixes.'
          labels: 'automation,lint'
          draft: false
